### PR TITLE
make oyente installable via setup.py

### PR DESCRIPTION
**Pull request by beaugunderson**
This is a work-in-progress pull request to add the ability to install oyente from pip with e.g. `pip install oyente`.

(We'd like to run oyente on the Augur contracts as part of our test infrastructure and this becomes much easier if we can install oyente using `pip install`.)

### CODE REVIEW

**Comment by loiluu** [comment]
Awesome, looks good to me.
@inian ?

**Comment by inian** [comment]
LGTM. @beaugunderson can you merge with master again? I will merge the PR once you have.

**Comment by beaugunderson** [comment]
@inian I'll rebase on `master` now 👍

I made this a 'work in progress' PR because I wasn't sure if you'd want to change how the settings are setup though (the ones in `global_params.py`); they could be made into command-line arguments, or environment variables, or be read from a file like `~/.oyenterc`...

(The reason being that if a user installs via `pip install` the `global_params.py` file will be somewhere under `/usr/local/lib/python2.7/site-packages`)

**Comment by beaugunderson** [comment]
I fixed `test_evm` somewhat; it seems like it was not 100% working before my changes...

**Comment by inian** [comment]
Yup, all the params in global_params.py can be taken in as command-line params, so that shouldn't be a problem. 
Are the tests working now? If so, I can merge this.

**Comment by beaugunderson** [comment]
@inian I tried running the tests against current `master` and they failed, so my branch is at least an improvement on that (most of the tests run)

**Comment by luongnt95** [comment]
@beaugunderson This error `No module named test_evm.evm_unit_test` occurred after pulling your PR and running the tests

**Comment by loiluu** [comment]
@inian can you please merge this PR?

**Comment by beaugunderson** [comment]
I've rebased to remove conflicts and also verified that tests work:

```
$ python test_evm.py
*****************************************************
                  *************
                      Start


===============Loading: addmodDivByZero1====================
WARNING:root:You are using an untested version of z3. 4.5.0 is the officially tested version
WARNING:root:You are using evm version 1.6.7. The supported version is 1.6.6
WARNING:root:You are using solc version 0.4.11, The supported version is 0.4.13
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  CallStack Attack: 	 False
INFO:symExec:	  Concurrency Bug: 	 False
INFO:symExec:	  Time Dependency: 	 False
INFO:symExec:	  Reentrancy bug exists: False
INFO:symExec:	====== Analysis Completed ======
no exit code returned


===============Loading: sdivByZero0====================
WARNING:root:You are using an untested version of z3. 4.5.0 is the officially tested version
WARNING:root:You are using evm version 1.6.7. The supported version is 1.6.6
WARNING:root:You are using solc version 0.4.11, The supported version is 0.4.13
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  CallStack Attack: 	 False
INFO:symExec:	  Concurrency Bug: 	 False
INFO:symExec:	  Time Dependency: 	 False
INFO:symExec:	  Reentrancy bug exists: False
INFO:symExec:	====== Analysis Completed ======
no exit code returned

etc.
```

**Comment by luongnt95** [comment]
Hey, @beaugunderson. It seems that you didn't set the global params variable UNIT_TEST to 2 or 3. Please check it again. [Here](https://github.com/melonproject/oyente/blob/master/CONTRIBUTING.md) is our doc. If you keep `UNIT_TEST = 0`, it's expected that all the tests will fail. The final result should be something like this:
test

**Comment by beaugunderson** [comment]
@luongnt95 thanks for explaining how `UNIT_TESTS` works; I've updated the code to ensure that my results are the same as in the screenshot you posted :)

**Comment by luongnt95** [comment]
Thanks @beaugunderson . It works now

**Comment by luongnt95** [comment]
@beaugunderson Can you delete the package on pypi so that I can update to the latest version of oyente?

**Comment by beaugunderson** [comment]
@luongnt95 what's your PyPi username? I'll add you as an owner

**Comment by luongnt95** [comment]
@beaugunderson my username: luongnt

**Comment by beaugunderson** [comment]
@luongnt95 ok, I've made you an owner and I also published 0.2.0 to PyPi :)

**Comment by luongnt95** [comment]
@beaugunderson Great!

**Pull request merged**
